@rootURL = http://localhost:3000
@apiEP = {{rootURL}}/api/v1

@authEP = {{apiEP}}/auth
@memberEP = {{apiEP}}/member
@adminEP = {{apiEP}}/admin
@superadminEP = {{apiEP}}/superadmin
@bookEP = {{apiEP}}/books
@borrowsEP = {{apiEP}}/borrows
@reviewsEP = {{apiEP}}/reviews

@sessionJWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYS5jb20iLCJpYXQiOjE3NjgzNjY5NzEsImV4cCI6MTc2ODQ1MzM3MX0.7d4FufyTWhpIyYIxamYKysqXIwmX7T4ml1klpxfEqxY
@renewJWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYS5jb20iLCJpYXQiOjE3NjgzNjY5NzEsImV4cCI6MTc3MDk1ODk3MX0.AOJBzwEwi0_d94TIxKx3RGWeGhdIZBYU0QGZqxCNG80
############################# AUTH
### login
POST {{authEP}}/login
Content-Type: application/json

{
    "email":"test@a.com",
    "password":"123"
}

### renew-jwt
GET {{authEP}}/renew-jwt
Authorization: {{renewJWT}}

############################## Member Route
### Create User
POST {{memberEP}}/register
Content-Type: application/json

{
    "email":"test3@a.com",
    "password":"123",
    "phone":"04583831",
    "fName":"testName",
    "lName":"testLastname"
}

### Get my details
GET {{memberEP}}/mydetails
Authorization: {{sessionJWT}}

### Update my details -> including password, not role or status
PATCH {{memberEP}}/update-mydetails
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "email":"lib2@a.com",
    "password":"123",
    "phone":"045838321",
    "fName":"testName2",
    "lName":"testLastname2",
    "status":"inactive",
    "role":"superadmin"
}

### Delete My account
DELETE {{memberEP}}/delete-account
Authorization: {{sessionJWT}}

################################# ADMIN-LIBRARIAN
### Get all Members
GET {{adminEP}}/users
Authorization: {{sessionJWT}}

### get a Member by id
GET {{adminEP}}/users/69667a436218554d7e21f0e4
Authorization: {{sessionJWT}}

### Change details of a Member (id params)
##Even you add password, it wont change it
### only updates on status
PATCH {{adminEP}}/update-user/69667a436218554d7e21f0e4
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "status":"active"
}

################################ SUPERADMIN
### get al librarians
GET {{superadminEP}}/librarians
Authorization: {{sessionJWT}}

### Create Librarian including password (role is required and must be admin)
POST {{superadminEP}}/create-librarian
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "email":"user11@a.com",
    "phone":"04583111",
    "fName":"testName",
    "lName":"testLastname",
    "password":"123",
    "role":"admin"
}
### Delete librarian use id
DELETE {{superadminEP}}/delete-librarian/69672210392db479fa64d58c
Authorization: {{sessionJWT}}

### Update librarian (not password allowed)
PATCH  {{superadminEP}}/update-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "email":"lib22@a.com",
    "phone":"2222",
    "fName":"testName",
    "lName":"testLastname",
    "password":"notupdate"
}

### Upgrade Member to LIBRARIAN
PATCH  {{superadminEP}}/upgrade-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "role":"admin"
}

### Downgrade librarian to MEMBER
PATCH  {{superadminEP}}/down-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "role":"member"
}