@rootURL = http://localhost:3000
@apiEP = {{rootURL}}/api/v1

@authEP = {{apiEP}}/auth
@memberEP = {{apiEP}}/member
@adminEP = {{apiEP}}/admin
@superadminEP = {{apiEP}}/superadmin
@bookEP = {{apiEP}}/books
@borrowsEP = {{apiEP}}/borrows
@reviewsEP = {{apiEP}}/reviews

@sessionJWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYS5jb20iLCJpYXQiOjE3NjkyNTc1NzMsImV4cCI6MTc2OTM0Mzk3M30.XQYsAUxZ5Y7dvmu82W1ymO5WRC4C4OZL8PEuz7_hvv0
@renewJWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAYS5jb20iLCJpYXQiOjE3NjkyNTc1NzMsImV4cCI6MTc3MTg0OTU3M30.2IPl5azOyQXmfETmzLLOqeyG4fExw6YjzmsRrVu7cNA

############################# AUTH Routes ##################
### login
POST {{authEP}}/login
Content-Type: application/json

{
    "email":"test@a.com",
    "password":"123"
}

### renew-jwt
GET {{authEP}}/renew-jwt
Authorization: {{renewJWT}}

############################## Member Route
### Create User
POST {{memberEP}}/register
Content-Type: application/json

{
    "email":"test3@a.com",
    "password":"123",
    "phone":"04583831",
    "fName":"testName",
    "lName":"testLastname"
}

### Get my details
GET {{memberEP}}/mydetails
Authorization: {{sessionJWT}}

### Update my details -> including password, not role or status
PATCH {{memberEP}}/update-mydetails
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "email":"lib2@a.com",
    "password":"123",
    "phone":"045838321",
    "fName":"testName2",
    "lName":"testLastname2",
    "status":"inactive",
    "role":"superadmin"
}

### Delete My account
DELETE {{memberEP}}/delete-account
Authorization: {{sessionJWT}}

################################# ADMIN-LIBRARIAN
### Get all Members
GET {{adminEP}}/users
Authorization: {{sessionJWT}}

### get a Member by id
GET {{adminEP}}/users/69667a436218554d7e21f0e4
Authorization: {{sessionJWT}}

### Change details of a Member (id params)
##Even you add password, it wont change it
### only updates on status
PATCH {{adminEP}}/update-user/69667a436218554d7e21f0e4
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "status":"active"
}

################################ SUPERADMIN
### get al librarians
GET {{superadminEP}}/librarians
Authorization: {{sessionJWT}}

### Create Librarian including password (role is required and must be admin)
POST {{superadminEP}}/create-librarian
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "email":"user11@a.com",
    "phone":"04583111",
    "fName":"testName",
    "lName":"testLastname",
    "password":"123",
    "role":"admin"
}
### Delete librarian use id
DELETE {{superadminEP}}/delete-librarian/69672210392db479fa64d58c
Authorization: {{sessionJWT}}

### Update librarian (not password allowed)
PATCH  {{superadminEP}}/update-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "email":"lib22@a.com",
    "phone":"2222",
    "fName":"testName",
    "lName":"testLastname",
    "password":"notupdate"
}

### Upgrade Member to LIBRARIAN
PATCH  {{superadminEP}}/upgrade-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "role":"admin"
}

### Downgrade librarian to MEMBER
PATCH  {{superadminEP}}/down-librarian/69666f3cb28c865ad784184a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
     "role":"member"
}


################################ BOOK Routes ###############
### Add book - Admin
POST {{bookEP}}/addbook
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "title":"book2",
    "status":"inactive",
    "author":"Garcia marquez",
    "isbn":"123231222",
    "description":"Fantasy book... ",
    "genre":"Fiction",
    "publicationYear": 1990,
    "typeEdition":"Hardcover",
    "quantityTotal": 65,
    "language":"spanish",
    "publisher":"Andes Editorial",
    "pages": 130,
    "country":"Venezuela"
}

### SearchBooks - any
GET {{bookEP}}/searchbooks?title=hu
Authorization: {{sessionJWT}}
### Search books - any - one input q
GET {{bookEP}}/searchbooks?q=garcia
Authorization: {{sessionJWT}}

### Search with pagination
GET {{bookEP}}/searchbooks?q=harry&page=2&limit=10
Authorization: {{sessionJWT}}

### Search with sorting (title asc)
GET {{bookEP}}/searchbooks?q=harry&sortBy=title&sortOrder=asc
Authorization: {{sessionJWT}}

### Search All Books -> admin
GET {{bookEP}}/searchallbooks?q=h&page=1&limit=10
Authorization: {{sessionJWT}}


// No filter q
####################### get all public books
GET {{bookEP}}/searchbooks?page=1&limit=10
Authorization: {{sessionJWT}}

// no filter q
####################### get all books -> admin
GET {{bookEP}}/searchallbooks?page=1&limit=10
Authorization: {{sessionJWT}}

### Get Book By Id -any user
GET {{bookEP}}/books/696f7eac6cf0858227674a1f

### Get Book By Id -admin
GET {{bookEP}}/allbooks/696f874d1d459a5025f70347
Authorization: {{sessionJWT}}

### modify book by id -> admin
PATCH {{bookEP}}/updatebook/696f7eac6cf0858227674a1f
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "title":"book4"
}

### delete book3
DELETE {{bookEP}}/deletebook/696f874d1d459a5025f70347
Authorization: {{sessionJWT}}

#################################  BORROWS ROUTES ############################

### create a borrow -> admin
POST {{borrowsEP}}/69667a436218554d7e21f0e4/696f7eac6cf0858227674a1f
Authorization: {{sessionJWT}}
Content-Type: application/json

{}

### create a borrow for myself -> member
POST {{borrowsEP}}/696f7eac6cf0858227674a1f
Authorization: {{sessionJWT}}
Content-Type: application/json

{}

### get my borrows -> member
GET {{borrowsEP}}/myborrows
Authorization: {{sessionJWT}}

### get all borrows -> admin
GET {{borrowsEP}}/allborrows
Authorization: {{sessionJWT}}

### return a book -> Admin
PATCH {{borrowsEP}}/returnbook/6974c7980669cda97174f19a
Authorization: {{sessionJWT}}

################# REVIEW ROUTES ######################
### Create a review for a book
POST {{reviewsEP}}/6974c7980669cda97174f19a
Authorization: {{sessionJWT}}
Content-Type: application/json

{
    "rating":4,
    "title":"Amazing Read",
    "comment":"Great book, really enjoyed it!"
}

### get ALL reviews ->admin
GET {{reviewsEP}}/allreviews
Authorization: {{sessionJWT}}

### Make review active -> admin
PATCH {{reviewsEP}}/updatereview/6974d3682985eef24f139b5d
Authorization: {{sessionJWT}}
Content-Type: application/json

{}

### Get Active Reviews for 1 book -> any
GET {{reviewsEP}}/book/696f7eac6cf0858227674a1f

### Get my active reviews only -> member
GET {{reviewsEP}}/myreviews
Authorization: {{sessionJWT}}