export const bookList = [
  {
    status: "active",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    description: "Classic novel about racial injustice in the American South.",
    publicationYear: 1960,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 12,
    language: "English",
    publisher: "HarperCollins",
    pages: 336,
    country: "USA",
  },
  {
    status: "active",
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    description: "Dystopian novel about totalitarian control and surveillance.",
    publicationYear: 1949,
    genre: "Science Fiction",
    typeEdition: "Paperback",
    quantityTotal: 15,
    language: "English",
    publisher: "Penguin",
    pages: 328,
    country: "UK",
  },
  {
    status: "active",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    description: "Romantic novel about manners, marriage and society.",
    publicationYear: 1813,
    genre: "Romance",
    typeEdition: "Paperback",
    quantityTotal: 10,
    language: "English",
    publisher: "Penguin Classics",
    pages: 279,
    country: "UK",
  },
  {
    status: "active",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "Story of wealth, love and the American dream.",
    publicationYear: 1925,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 8,
    language: "English",
    publisher: "Scribner",
    pages: 180,
    country: "USA",
  },
  {
    status: "active",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "9780547928227",
    description: "Fantasy adventure of Bilbo Baggins in Middle-earth.",
    publicationYear: 1937,
    genre: "Fantasy",
    typeEdition: "Hardcover",
    quantityTotal: 14,
    language: "English",
    publisher: "Houghton Mifflin",
    pages: 310,
    country: "UK",
  },
  {
    status: "active",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    isbn: "9780747532699",
    description: "A young wizard begins his magical journey at Hogwarts.",
    publicationYear: 1997,
    genre: "Fantasy",
    typeEdition: "Paperback",
    quantityTotal: 20,
    language: "English",
    publisher: "Bloomsbury",
    pages: 223,
    country: "UK",
  },
  {
    status: "active",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    isbn: "9780307474278",
    description: "Mystery thriller involving secret societies and symbols.",
    publicationYear: 2003,
    genre: "Mystery",
    typeEdition: "Paperback",
    quantityTotal: 11,
    language: "English",
    publisher: "Anchor",
    pages: 454,
    country: "USA",
  },
  {
    status: "active",
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "A shepherd travels in search of his personal legend.",
    publicationYear: 1988,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 9,
    language: "English",
    publisher: "HarperOne",
    pages: 208,
    country: "Brazil",
  },
  {
    status: "active",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    isbn: "9780156012195",
    description: "Philosophical tale about a young prince exploring planets.",
    publicationYear: 1943,
    genre: "Children's",
    typeEdition: "Paperback",
    quantityTotal: 7,
    language: "English",
    publisher: "Mariner Books",
    pages: 96,
    country: "France",
  },
  {
    status: "active",
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbn: "9780307588371",
    description: "Psychological thriller about a missing wife.",
    publicationYear: 2012,
    genre: "Mystery",
    typeEdition: "Paperback",
    quantityTotal: 13,
    language: "English",
    publisher: "Crown",
    pages: 432,
    country: "USA",
  },
  {
    status: "active",
    title: "The Shining",
    author: "Stephen King",
    isbn: "9780307743657",
    description: "A family isolated in a haunted hotel descends into horror.",
    publicationYear: 1977,
    genre: "Horror",
    typeEdition: "Paperback",
    quantityTotal: 6,
    language: "English",
    publisher: "Anchor",
    pages: 447,
    country: "USA",
  },
  {
    status: "active",
    title: "Dune",
    author: "Frank Herbert",
    isbn: "9780441013593",
    description: "Epic science fiction saga set on desert planet Arrakis.",
    publicationYear: 1965,
    genre: "Science Fiction",
    typeEdition: "Paperback",
    quantityTotal: 16,
    language: "English",
    publisher: "Ace",
    pages: 412,
    country: "USA",
  },
  {
    status: "active",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    isbn: "9781451673319",
    description: "Future where books are banned and burned.",
    publicationYear: 1953,
    genre: "Science Fiction",
    typeEdition: "Paperback",
    quantityTotal: 10,
    language: "English",
    publisher: "Simon & Schuster",
    pages: 249,
    country: "USA",
  },
  {
    status: "active",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    isbn: "9780385490818",
    description: "Dystopian society where women lose all rights.",
    publicationYear: 1985,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 12,
    language: "English",
    publisher: "Anchor",
    pages: 311,
    country: "Canada",
  },
  {
    status: "active",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    description: "History of humankind from evolution to modern era.",
    publicationYear: 2011,
    genre: "Non-Fiction",
    typeEdition: "Paperback",
    quantityTotal: 18,
    language: "English",
    publisher: "Harper",
    pages: 498,
    country: "Israel",
  },
  {
    status: "active",
    title: "Educated",
    author: "Tara Westover",
    isbn: "9780399590504",
    description: "Memoir of a woman who escapes survivalist upbringing.",
    publicationYear: 2018,
    genre: "Biography",
    typeEdition: "Paperback",
    quantityTotal: 8,
    language: "English",
    publisher: "Random House",
    pages: 334,
    country: "USA",
  },
  {
    status: "active",
    title: "Becoming",
    author: "Michelle Obama",
    isbn: "9781524763138",
    description: "Memoir of former First Lady Michelle Obama.",
    publicationYear: 2018,
    genre: "Biography",
    typeEdition: "Hardcover",
    quantityTotal: 10,
    language: "English",
    publisher: "Crown",
    pages: 448,
    country: "USA",
  },
  {
    status: "active",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    isbn: "9780553296983",
    description: "Diary of a Jewish girl hiding during WWII.",
    publicationYear: 1947,
    genre: "Biography",
    typeEdition: "Paperback",
    quantityTotal: 6,
    language: "English",
    publisher: "Bantam",
    pages: 283,
    country: "Netherlands",
  },
  {
    status: "active",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    isbn: "9781594631931",
    description: "Story of friendship and redemption in Afghanistan.",
    publicationYear: 2003,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 11,
    language: "English",
    publisher: "Riverhead",
    pages: 371,
    country: "USA",
  },
  {
    status: "active",
    title: "The Book Thief",
    author: "Markus Zusak",
    isbn: "9780375842207",
    description: "Girl steals books in Nazi Germany.",
    publicationYear: 2005,
    genre: "Fiction",
    typeEdition: "Paperback",
    quantityTotal: 9,
    language: "English",
    publisher: "Knopf",
    pages: 552,
    country: "Australia",
  },
  {
    status: "active",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    isbn: "9780439023481",
    description: "Dystopian survival competition for teenagers.",
    publicationYear: 2008,
    genre: "Science Fiction",
    typeEdition: "Paperback",
    quantityTotal: 17,
    language: "English",
    publisher: "Scholastic",
    pages: 374,
    country: "USA",
  },
  {
    status: "active",
    title: "The Fault in Our Stars",
    author: "John Green",
    isbn: "9780142424179",
    description: "Teen romance dealing with illness and love.",
    publicationYear: 2012,
    genre: "Romance",
    typeEdition: "Paperback",
    quantityTotal: 10,
    language: "English",
    publisher: "Dutton",
    pages: 313,
    country: "USA",
  },
  {
    status: "active",
    title: "The Martian",
    author: "Andy Weir",
    isbn: "9780553418026",
    description: "Astronaut stranded on Mars fights to survive.",
    publicationYear: 2011,
    genre: "Science Fiction",
    typeEdition: "Paperback",
    quantityTotal: 14,
    language: "English",
    publisher: "Crown",
    pages: 387,
    country: "USA",
  },
  {
    status: "active",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    isbn: "9780756404741",
    description: "Epic fantasy tale of a legendary magician.",
    publicationYear: 2007,
    genre: "Fantasy",
    typeEdition: "Paperback",
    quantityTotal: 7,
    language: "English",
    publisher: "DAW Books",
    pages: 662,
    country: "USA",
  },
  {
    status: "active",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    isbn: "9781250301697",
    description: "Psychological thriller about a silent murderer.",
    publicationYear: 2019,
    genre: "Mystery",
    typeEdition: "Paperback",
    quantityTotal: 13,
    language: "English",
    publisher: "Celadon",
    pages: 336,
    country: "UK",
  },
  {
    status: "active",
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    description: "Guide to building good habits and breaking bad ones.",
    publicationYear: 2018,
    genre: "Non-Fiction",
    typeEdition: "Paperback",
    quantityTotal: 19,
    language: "English",
    publisher: "Avery",
    pages: 320,
    country: "USA",
  },
  {
    status: "active",
    title: "Dracula",
    author: "Bram Stoker",
    isbn: "9780486411095",
    description: "Classic vampire horror novel.",
    publicationYear: 1897,
    genre: "Horror",
    typeEdition: "Paperback",
    quantityTotal: 5,
    language: "English",
    publisher: "Dover",
    pages: 418,
    country: "UK",
  },
  {
    status: "active",
    title: "Frankenstein",
    author: "Mary Shelley",
    isbn: "9780486282114",
    description: "Scientist creates a living creature with tragic results.",
    publicationYear: 1818,
    genre: "Horror",
    typeEdition: "Paperback",
    quantityTotal: 6,
    language: "English",
    publisher: "Dover",
    pages: 280,
    country: "UK",
  },
  {
    status: "active",
    title: "The History of the Ancient World",
    author: "Susan Wise Bauer",
    isbn: "9780393059748",
    description: "Comprehensive history of early civilizations.",
    publicationYear: 2007,
    genre: "History",
    typeEdition: "Paperback",
    quantityTotal: 4,
    language: "English",
    publisher: "W.W. Norton",
    pages: 896,
    country: "USA",
  },
  {
    status: "active",
    title: "Charlotte's Web",
    author: "E.B. White",
    isbn: "9780064400558",
    description: "Beloved children's story about friendship and a pig.",
    publicationYear: 1952,
    genre: "Children's",
    typeEdition: "Paperback",
    quantityTotal: 8,
    language: "English",
    publisher: "HarperCollins",
    pages: 192,
    country: "USA",
  },
];
